### ISSUE TITLE
[BUG] Handle version conflict with backoff retry

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/opensearch-spark#145]
```
23/11/09 07:42:21 WARN FlintREPL: Fail to update the last update time of the flint instance UlFXdkxHVDE3OGdsdWVfMQ==
org.opensearch.OpenSearchStatusException: OpenSearch exception [type=version_conflict_engine_exception, reason=[UlFXdkxHVDE3OGdsdWVfMQ==]: version conflict, required seqNo [2247], primary term [3]. current document has seqNo [2250] and primary term [3]]
	at org.opensearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:207) ~[opensearch-spark-standalone_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
	at org.opensearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2228) ~[opensearch-spark-standalone_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
	at org.opensearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2205) ~[opensearch-spark-standalone_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
	at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1924) ~[opensearch-spark-standalone_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
	at org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1877) ~[opensearch-spark-standalone_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
	at org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1845) ~[opensearch-spark-standalone_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
	at org.opensearch.client.RestHighLevelClient.update(RestHighLevelClient.java:1022) ~[opensearch-spark-standalone_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
	at org.opensearch.flint.core.storage.OpenSearchUpdater.updateIf(OpenSearchUpdater.java:68) ~[opensearch-spark-standalone_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
	at org.apache.spark.sql.FlintREPL$$anon$1.run(FlintREPL.scala:621) ~[opensearch-spark-sql-application_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	Suppressed: org.opensearch.client.ResponseException: method [POST], host [https://search-flint-loadtest-2-11-7do6qjpsombdtavf5r74zvs4dy.us-west-2.es-release.amazonaws.com], URI [/.query_execution_request_glue_1/_update/UlFXdkxHVDE3OGdsdWVfMQ==?refresh=wait_for&timeout=1m], status line [HTTP/1.1 409 Conflict]
{"error":{"root_cause":[{"type":"version_conflict_engine_exception","reason":"[UlFXdkxHVDE3OGdsdWVfMQ==]: version conflict, required seqNo [2247], primary term [3]. current document has seqNo [2250] and primary term [3]","index":".query_execution_request_glue_1","shard":"0","index_uuid":"wPKu9jE2Q1SI9DleTAy5cw"}],"type":"version_conflict_engine_exception","reason":"[UlFXdkxHVDE3OGdsdWVfMQ==]: version conflict, required seqNo [2247], primary term [3]. current document has seqNo [2250] and primary term [3]","index":".query_execution_request_glue_1","shard":"0","index_uuid":"wPKu9jE2Q1SI9DleTAy5cw"},"status":409}
		at org.opensearch.client.RestClient.convertResponse(RestClient.java:375) ~[opensearch-spark-standalone_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
		at org.opensearch.client.RestClient.performRequest(RestClient.java:345) ~[opensearch-spark-standalone_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
		at org.opensearch.client.RestClient.performRequest(RestClient.java:320) ~[opensearch-spark-standalone_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
		at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1911) ~[opensearch-spark-standalone_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
		at org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1877) ~[opensearch-spark-standalone_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
		at org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1845) ~[opensearch-spark-standalone_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
		at org.opensearch.client.RestHighLevelClient.update(RestHighLevelClient.java:1022) ~[opensearch-spark-standalone_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
		at org.opensearch.flint.core.storage.OpenSearchUpdater.updateIf(OpenSearchUpdater.java:68) ~[opensearch-spark-standalone_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
		at org.apache.spark.sql.FlintREPL$$anon$1.run(FlintREPL.scala:621) ~[opensearch-spark-sql-application_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
		at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
		at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by kaituo** [comment]
Changed to add initial delay to reduce likelihood of conflict

**Comment by dai-chen** [comment]
This retry (essential compare-and-set operation) should happen on higher level and thus not covered in PR above.
