### ISSUE TITLE
[BUG] FlintREPL should handle nullable JobStartTime when startup.

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/opensearch-spark#152]
jobStartTime is nullable value. Plugin does not write jobStartTime field when create session. Spark job should write jobStartTime.

```
23/11/13 09:00:07 WARN FlintREPL: Fail to update the last update time of the flint instance R3N4WndiTUtlWW15czM=
java.util.NoSuchElementException: key not found: jobStartTime
	at scala.collection.MapLike.default(MapLike.scala:236) ~[scala-library-2.12.15.jar:?]
	at scala.collection.MapLike.default$(MapLike.scala:235) ~[scala-library-2.12.15.jar:?]
	at scala.collection.AbstractMap.default(Map.scala:65) ~[scala-library-2.12.15.jar:?]
	at scala.collection.MapLike.apply(MapLike.scala:144) ~[scala-library-2.12.15.jar:?]
	at scala.collection.MapLike.apply$(MapLike.scala:143) ~[scala-library-2.12.15.jar:?]
	at scala.collection.AbstractMap.apply(Map.scala:65) ~[scala-library-2.12.15.jar:?]
	at org.opensearch.flint.app.FlintInstance$.deserializeFromMap(FlintInstance.scala:78) ~[opensearch-spark-standalone_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
	at org.apache.spark.sql.FlintREPL$$anon$1.run(FlintREPL.scala:844) ~[opensearch-spark-sql-application_2.12-0.1.0.jar:0.1.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
```

**Comment by kaituo** [comment]
fixed in https://github.com/opensearch-project/opensearch-spark/pull/153
