### ISSUE TITLE
[BUG] delete index request to OpenSearch Serverless collection fails

### ISSUE THREAD

**Issue by ykmr1224** [opensearch-project/opensearch-spark#634]
**What is the bug?**
When OpenSearch Serverless collection is used as index store, it fails to delete index due to unrecognized parameters `master_timeout`, and `timeout`.
It is because those options are automatically set by the OpenSearch client library but serverless collection doesn't support them.

```
OpenSearch exception [type=illegal_argument_exception, reason=request [/flint_spark_catalog_default_ci_test_name_and_age_index] contains unrecognized parameters: [master_timeout], [timeout]]
OpenSearchStatusException[OpenSearch exception [type=illegal_argument_exception, reason=request [/flint_spark_catalog_default_ci_test_name_and_age_index] contains unrecognized parameters: [master_timeout], [timeout]]]
	at org.opensearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:207)
	at org.opensearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2228)
	at org.opensearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2205)
	at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1924)
	at org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1877)
	at org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1845)
	at org.opensearch.client.IndicesClient.delete(IndicesClient.java:118)
	at org.opensearch.flint.spark.FlintSparkSuite.$anonfun$deleteTestIndex$1(FlintSparkSuite.scala:82)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at org.opensearch.flint.spark.FlintSparkSuite.deleteTestIndex(FlintSparkSuite.scala:64)
	at org.opensearch.flint.spark.FlintSparkSuite.deleteTestIndex$(FlintSparkSuite.scala:63)
	at org.opensearch.flint.spark.FlintSparkCoveringIndexITSuite.deleteTestIndex(FlintSparkCoveringIndexITSuite.scala:20)
	at org.opensearch.flint.spark.FlintSparkCoveringIndexITSuite.afterEach(FlintSparkCoveringIndexITSuite.scala:38)
	at org.scalatest.BeforeAndAfterEach.$anonfun$runTest$1(BeforeAndAfterEach.scala:247)
	at org.scalatest.Status.$anonfun$withAfterEffect$1(Status.scala:377)
	at org.scalatest.Status.$anonfun$withAfterEffect$1$adapted(Status.scala:373)
	at org.scalatest.FailedStatus$.whenCompleted(Status.scala:505)
	at org.scalatest.Status.withAfterEffect(Status.scala:373)
	at org.scalatest.Status.withAfterEffect$(Status.scala:371)
	at org.scalatest.FailedStatus$.withAfterEffect(Status.scala:477)
	at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:246)
	at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:227)
	at org.apache.spark.SparkFunSuite.runTest(SparkFunSuite.scala:64)
	at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTests$1(AnyFunSuiteLike.scala:269)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.funsuite.AnyFunSuiteLike.runTests(AnyFunSuiteLike.scala:269)
	at org.scalatest.funsuite.AnyFunSuiteLike.runTests$(AnyFunSuiteLike.scala:268)
	at org.scalatest.funsuite.AnyFunSuite.runTests(AnyFunSuite.scala:1564)
	at org.scalatest.Suite.run(Suite.scala:1114)
	at org.scalatest.Suite.run$(Suite.scala:1096)
	at org.scalatest.funsuite.AnyFunSuite.org$scalatest$funsuite$AnyFunSuiteLike$$super$run(AnyFunSuite.scala:1564)
	at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$run$1(AnyFunSuiteLike.scala:273)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.funsuite.AnyFunSuiteLike.run(AnyFunSuiteLike.scala:273)
	at org.scalatest.funsuite.AnyFunSuiteLike.run$(AnyFunSuiteLike.scala:272)
	at org.apache.spark.SparkFunSuite.org$scalatest$BeforeAndAfterAll$$super$run(SparkFunSuite.scala:64)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at org.apache.spark.SparkFunSuite.run(SparkFunSuite.scala:64)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:47)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1321)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1315)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1315)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:992)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:970)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1481)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:970)
	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:43)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:26)
	Suppressed: org.opensearch.client.ResponseException: method [DELETE], host [https://8lcitp965p4i2ed4r8zj.us-west-2.aoss.amazonaws.com:443], URI [/flint_spark_catalog_default_ci_test_name_and_age_index?master_timeout=30s&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=true&ignore_throttled=false&timeout=30s], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/flint_spark_catalog_default_ci_test_name_and_age_index] contains unrecognized parameters: [master_timeout], [timeout]"}],"type":"illegal_argument_exception","reason":"request [/flint_spark_catalog_default_ci_test_name_and_age_index] contains unrecognized parameters: [master_timeout], [timeout]"},"status":400}
		at org.opensearch.client.RestClient.convertResponse(RestClient.java:375)
		at org.opensearch.client.RestClient.performRequest(RestClient.java:345)
		at org.opensearch.client.RestClient.performRequest(RestClient.java:320)
		at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1911)
		... 55 more
```

**How can one reproduce the bug?**
1. Run tests in `FlintSparkCoveringIndexITSuite` while serverless collection endpoint is specified as OpenSearch server. (This currently requires some hack due to parameter difference, etc.)

**What is the expected behavior?**
It should be able to delete index without error.

**What is your host/environment?**
 - OS: MacOS
 - Version 0.5
 - Plugins n/a

**Do you have any screenshots?**
n/a

**Do you have any additional context?**
We moved VACUUM to spark side, and we need index delete from spark.

**Comment by ykmr1224** [comment]
Currently, checking if the serverless API behavior is a spec or a bug.

**Comment by ykmr1224** [comment]
OpenSearch serverless does not support `master_timeout` and `timeout` params for deleteIndex. (bulk and _doc supports only `timeout`)
