### ISSUE TITLE
[BUG] Map types not supported in FlintDataType

### ISSUE THREAD

**Issue by engechas** [opensearch-project/opensearch-spark#908]
**What is the bug?**
FlintDataType doesn't support MAP types from Glue

```
24/11/14 18:18:54 ERROR DefaultOptimisticTransaction: Rolling back transient log due to transaction operation failure
java.lang.IllegalStateException: unsupported data type: MAP<STRING, STRING>
	at org.apache.spark.sql.flint.datatype.FlintDataType$.serializeField(FlintDataType.scala:166) ~[opensearch-spark-standalone_2.12-latest.jar:0.7.0-SNAPSHOT]
	at org.apache.spark.sql.flint.datatype.FlintDataType$.$anonfun$serializeJValue$1(FlintDataType.scala:121) ~[opensearch-spark-standalone_2.12-latest.jar:0.7.0-SNAPSHOT]
```

**How can one reproduce the bug?**
1. Create a glue table with a map type
2. Attempt to create a materialized view of the table

**What is the expected behavior?**
MAP types should be supported. Maps can be converted to OpenSearch objects

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by dblock** [comment]
[[Catch All Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/reta), [3](https://github.com/andrross/)]
