### ISSUE TITLE
[BUG] resource_already_exists_exception when using async OpenSearch service

### ISSUE THREAD

**Issue by seankao-az** [opensearch-project/opensearch-spark#950]
**What is the bug?**
If the OpenSearch service used for managing flint index handles requests asynchronously, we might get error when creating Flint index:
```
OpenSearchStatusException[OpenSearch exception [type=resource_already_exists_exception, reason=Update to the indices [(redacted)] failed due to either concurrent update or deletion of the indices]]
    at org.opensearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:207)
    at org.opensearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2228)
    at org.opensearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2205)
    at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1924)
    at org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1894)
    at org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1858)
    at org.opensearch.client.IndicesClient.putMapping(IndicesClient.java:373)
```
This is due to requests for update mapping made to the OpenSearch service while create index request is still being processed.

**How can one reproduce the bug?**
Use Amazon OpenSearch Serverless and try to create Flint index. It might happen but not consistently.

**What is the expected behavior?**
Index creation should succeed without error.

**Comment by seankao-az** [comment]
Upon further investigation, AOSS internal operations (update index settings) can also conflict with our update mappings request and result in this failure. AOSS support suggests us retry our request in such case, which is already implemented and merged.
